### ISSUE TITLE
Doesn't work with Crosswalk

### ISSUE THREAD

**Issue by ozexpert** [VVelda/device-feedback#3]
```
error: cannot find symbol
        webView.setSoundEffectsEnabled(false);
               ^
  symbol:   method setSoundEffectsEnabled(boolean)
  location: variable webView of type CordovaWebView

error: cannot find symbol
            webView.performHapticFeedback(args.getInt(VIBRATE_TYPE_INDEX));
                   ^
  symbol:   method performHapticFeedback(int)
  location: variable webView of type CordovaWebView
```

Not sure why webView cannot find those methods.. i thought those methods are overridden from apache webView from crosswalk point of view. Have you noticed? 

Btw, it's great plugin!

**Comment by VVelda** [comment]
Hello,
Thank You for feedback. But there is no problem with the plugin. Crosswallk isn't compatible with Cordova, even thought they are saying that is, but it's just not true, because it is impossible.

I'm going to write more there https://github.com/VVelda/device-feedback/pull/4.

If you wanna do, you can make bug report for Crosswalk https://crosswalk-project.org/jira/ to add this methods to their webView to make it more Cordova-Android compatible.

But, I have made new branch for crosswalk with changes according to https://github.com/VVelda/device-feedback/pull/4 and you can install it this way `cordova plugin add https://github.com/VVelda/device-feedback/#crosswalk` 

Can You then confirm, that it works for You?

**Comment by ozexpert** [comment]
Works perfect. Thanks!
You could add that to your document :-) :+1:

**Comment by VVelda** [comment]
Done!
Thanks for response.

**Comment by VVelda** [comment]
Master branch should works well now also with Crosswalk. Thus, I deleted crosswalk branch.

**Comment by ozexpert** [comment]
Got it. Thanks for the update :-)
